import { expect, test } from "@playwright/test";

test("Anna creates, evaluates, and coaches one live SkillQuest", async ({ page }) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("console", (message) => { if (message.type() === "error") errors.push(message.text()); });
  await page.goto("/");
  const frame = page.frameLocator("iframe#app");
  await frame.getByRole("link", { name: /Build my practice path/ }).click();
  await frame.getByLabel("Your learning goal").fill("I want to deliver and explain a clear five-minute product story that helps my team remember the user problem and next action.");
  await frame.locator(".source-material > summary").click();
  await frame.getByLabel("Learning material or work sample").fill("Current outline: internal project context, three feature bullets, architecture notes, and a closing roadmap. The user problem appears only after the feature list.");
  await frame.getByRole("button", { name: /Let Anna build my path/ }).click();
  await expect(frame.getByText("Designed by Anna")).toBeVisible({ timeout: 210_000 });
  await expect(frame.locator(".quest-node")).toHaveCount(12);
  await frame.locator("a.quest-node").first().click();
  await frame.locator(".criteria-checks input").evaluateAll((nodes) => nodes.forEach((node) => node.click()));
  await frame.getByLabel(/Your work or learning material/).fill("Revised outline: user problem, consequence, product decision, evidence, next action. Opening script: Teams lose context when decisions are scattered across tools.");
  await frame.getByLabel("What did you do or change?").fill("I wrote a five-part product story outline, recorded a two-minute opening, and moved the user problem before the feature explanation.");
  await frame.getByLabel(/What felt difficult or surprising/).fill("Moving the user problem into the opening made the product choice easier to follow. My next attempt should remove one internal term.");
  await frame.getByRole("button", { name: /Review my work/ }).click();
  await expect(frame.getByRole("dialog")).toBeVisible({ timeout: 210_000 });
  await frame.getByRole("dialog").getByRole("button", { name: "Review feedback" }).evaluate((button) => button.click());
  await expect(frame.getByText(/Work review · Anna/)).toBeVisible();
  await frame.getByRole("link", { name: "Coach" }).first().evaluate((link) => link.click());
  await frame.locator(".mentor-empty button").first().click();
  await frame.getByRole("button", { name: "Send" }).click();
  const reply = frame.locator(".mentor-message--assistant").last();
  await expect(reply.locator("p")).toBeVisible({ timeout: 210_000 });
  await expect(reply).not.toContainText("Local fallback");
  await expect(reply.locator("p")).not.toHaveText(/^\s*[\[{]/);
  expect(errors).toEqual([]);
});
